### PR TITLE
Fix support for python3

### PR DESCRIPTION
**Pull request by josegonzalez**
My limited testing - adding head and tail rules - has this working as desired, so I figured I would make a pull request :)

### CODE REVIEW

**Comment by kustodian** [comment]
@josegonzalez could you please rebase your changes from master I just submitted and we will do more testing to see if everything works correctly, then merge your pull request.

Sorry for waiting this long.

**Comment by josegonzalez** [comment]
Please test this to make sure I didn't break anything! :)

**Comment by kustodian** [comment]
Thanks for helping out. I did merge your changes, but GH didn't detect them.

I had to fix a few issues (`compare_dictionaires`) didn't work correctly, which you can check in this commit https://github.com/Nordeus/ansible_iptables_raw/commit/e7195e41f6fd2f7770c125cba0e48b88270c94f0.

**Comment by josegonzalez** [comment]
No worries, works for me :)

**Pull request closed without merging**
